
title: Manu Goyal  # You can add your name here

logo: IMG_4165.jpg # Use a relative path to logo image 

description: Data Scientist

show_downloads: False # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: goyalm685@gmail.com # Allow visitors to contact you
